name: vspaint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - pip=22.3.1
  - numpy=1.23.5
  - pandas=1.5.2
  - matplotlib=3.6.2
  - seaborn=0.12.2
  - umap-learn=0.5.3
  - tabulate=0.9.0
  - openpyxl=3.1.2
  - pip:
      - cython==3.0.5
      - exceptiongroup==1.1.1
      - greenlet==2.0.2
      - h5py==3.8.0
      - iniconfig==2.0.0
      - joblib==1.1.1
      - kaleido==0.2.1
      - matplotlib-venn==0.11.9
      - pluggy==1.0.0
      - pyarrow==11.0.0
      - pycytominer==0.2.0
      - pytest==7.2.2
      - scipy==1.8.1
      - sdf==0.3.5
      - sqlalchemy==1.4.47
      - tomli==2.0.1